CreateConVar("phantom_step_enabled", "1", 128, "on or off")
CreateConVar("phantom_step_chance", "100", 128, "how often it happens")
CreateConVar("phantom_step_min", "20", 128, "fastest it can go")
CreateConVar("phantom_step_max", "60", 128, "slowest it can go")
CreateConVar("phantom_step_vol_min", "0.3", 128, "quietest it gets")
CreateConVar("phantom_step_vol_max", "0.8", 128, "loudest it gets")
CreateConVar("phantom_step_dist_start", "150", 128, "how far behind")
CreateConVar("phantom_step_spread", "40", 128, "how wide")
CreateConVar("phantom_step_burst_chance", "30", 128, "chance for a bunch of steps")
CreateConVar("phantom_step_burst_count", "4", 128, "how many steps in a row")
CreateConVar("phantom_step_burst_speed", "0.25", 128, "how fast they follow")
CreateConVar("phantom_step_patter_towards", "1", 128, "do they move closer")
CreateConVar("phantom_step_debug", "0", 128, "draw boxes so i can see")
