hook.Add("PopulateToolMenu", "x", function()
spawnmenu.AddToolMenuOption("Utilities", "Horror", "a", "Evil Footsteps", "", "", function(p)
p:ClearControls()
p:Help("malq")
p:CheckBox("enable", "phantom_step_enabled")
p:NumSlider("chance", "phantom_step_chance", 0, 100, 0)
p:NumSlider("min", "phantom_step_min", 1, 120, 0)
p:NumSlider("max", "phantom_step_max", 1, 300, 0)
p:Help("vol")
p:NumSlider("min v", "phantom_step_vol_min", 0, 1, 2)
p:NumSlider("max v", "phantom_step_vol_max", 0, 1, 2)
p:Help("pos")
p:NumSlider("dist", "phantom_step_dist_start", 20, 500, 0)
p:NumSlider("spread", "phantom_step_spread", 0, 200, 0)
p:Help("burst")
p:NumSlider("b chance", "phantom_step_burst_chance", 0, 100, 0)
p:CheckBox("lerp", "phantom_step_patter_towards")
p:NumSlider("count", "phantom_step_burst_count", 2, 15, 0)
p:NumSlider("speed", "phantom_step_burst_speed", 0.05, 1, 2)
p:Help("debug")
p:CheckBox("debug", "phantom_step_debug")
local b = p:Button("test")
b.DoClick = function() 
LocalPlayer():ConCommand("phantom_step_test") 
end
end)
end)
